# Generated by Django 3.0.5 on 2020-04-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('animalID', models.AutoField(primary_key=True, serialize=False)),
                ('animalName', models.CharField(max_length=30)),
                ('animalAge', models.IntegerField()),
                ('animalGender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='animalFood',
            fields=[
                ('foodID', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(choices=[('bamboo', 'bamboo'), ('eucalyptus', 'eucalyptus'), ('grass', 'grass'), ('nuts', 'nuts'), ('meat', 'meat'), ('fish', 'fish'), ('lettuce', 'lettuce'), ('banana', 'banana'), ('worms', 'worms'), ('mice', 'mice')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('employeeType', models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff'), ('Medic', 'Medical'), ('CEO', 'CEO'), ('Maintanence', 'Maintanence'), ('Custodian', 'Custodian')], max_length=11)),
                ('employeeDOB', models.DateField()),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='park',
            fields=[
                ('parkID', models.AutoField(primary_key=True, serialize=False)),
                ('parkName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='specialNeed',
            fields=[
                ('needID', models.AutoField(primary_key=True, serialize=False)),
                ('need', models.CharField(max_length=30)),
                ('care', models.CharField(max_length=30)),
                ('restrictions', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('volunteerID', models.AutoField(primary_key=True, serialize=False)),
                ('vFname', models.CharField(max_length=30)),
                ('vLname', models.CharField(max_length=30)),
                ('volunteerDOB', models.DateField()),
                ('hours', models.IntegerField()),
                ('parkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.park')),
            ],
        ),
        migrations.CreateModel(
            name='volunteerPhone',
            fields=[
                ('vPhoneID', models.AutoField(primary_key=True, serialize=False)),
                ('vPhoneNumber', models.IntegerField()),
                ('volunteerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='specialAnimal',
            fields=[
                ('specialID', models.AutoField(primary_key=True, serialize=False)),
                ('animalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.animal')),
                ('needID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specialNeed')),
            ],
        ),
        migrations.CreateModel(
            name='exhibit',
            fields=[
                ('exhibitID', models.AutoField(primary_key=True, serialize=False)),
                ('exhibitName', models.CharField(max_length=30)),
                ('animalType', models.CharField(max_length=30)),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.animalFood')),
                ('parkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.park')),
            ],
        ),
        migrations.CreateModel(
            name='employeePhone',
            fields=[
                ('ePhoneID', models.AutoField(primary_key=True, serialize=False)),
                ('ePhoneNumber', models.IntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='exhibitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.exhibit'),
        ),
    ]
